"""
validation_report_types.py - Data types for eIDAS validation reports

Contains the SubIndication enum per ETSI EN 319 102-1.
Extracted from validation_report.py to keep each module under 400 lines.
"""

from __future__ import annotations

from enum import Enum


class SubIndication(str, Enum):
    """Sub-indication per ETSI EN 319 102-1 Section 5.1.2."""

    # For TOTAL_FAILED
    FORMAT_FAILURE = "FORMAT_FAILURE"
    HASH_FAILURE = "HASH_FAILURE"
    SIG_CRYPTO_FAILURE = "SIG_CRYPTO_FAILURE"
    REVOKED = "REVOKED"
    SIG_CONSTRAINTS_FAILURE = "SIG_CONSTRAINTS_FAILURE"
    CHAIN_CONSTRAINTS_FAILURE = "CHAIN_CONSTRAINTS_FAILURE"
    CERTIFICATE_CHAIN_GENERAL_FAILURE = "CERTIFICATE_CHAIN_GENERAL_FAILURE"
    CRYPTO_CONSTRAINTS_FAILURE = "CRYPTO_CONSTRAINTS_FAILURE"
    EXPIRED = "EXPIRED"
    NOT_YET_VALID = "NOT_YET_VALID"
    POLICY_PROCESSING_ERROR = "POLICY_PROCESSING_ERROR"
    SIGNATURE_POLICY_NOT_AVAILABLE = "SIGNATURE_POLICY_NOT_AVAILABLE"
    TIMESTAMP_ORDER_FAILURE = "TIMESTAMP_ORDER_FAILURE"

    # For INDETERMINATE
    NO_SIGNING_CERTIFICATE_FOUND = "NO_SIGNING_CERTIFICATE_FOUND"
    NO_CERTIFICATE_CHAIN_FOUND = "NO_CERTIFICATE_CHAIN_FOUND"
    REVOKED_NO_POE = "REVOKED_NO_POE"
    REVOKED_CA_NO_POE = "REVOKED_CA_NO_POE"
    OUT_OF_BOUNDS_NO_POE = "OUT_OF_BOUNDS_NO_POE"
    OUT_OF_BOUNDS_NOT_REVOKED = "OUT_OF_BOUNDS_NOT_REVOKED"
    CRYPTO_CONSTRAINTS_FAILURE_NO_POE = "CRYPTO_CONSTRAINTS_FAILURE_NO_POE"
    NO_POE = "NO_POE"
    TRY_LATER = "TRY_LATER"
    SIGNED_DATA_NOT_FOUND = "SIGNED_DATA_NOT_FOUND"
