#!/usr/bin/env python3
"""
create_test_pdfs.py - Utility to create test PDF fixtures

Author: Homero Thompson del Lago del Terror

Usage:
    uv run python tests/fixtures/create_test_pdfs.py
    uv run python tests/fixtures/create_test_pdfs.py --all
    uv run python tests/fixtures/create_test_pdfs.py --unsigned
    uv run python tests/fixtures/create_test_pdfs.py --signed
"""

import argparse
from pathlib import Path

import fitz  # PyMuPDF


def create_unsigned_pdf(output_path: Path) -> None:
    """Create a simple unsigned PDF for testing."""
    print(f"Creating unsigned PDF: {output_path}")

    doc = fitz.open()
    page = doc.new_page(width=612, height=792)  # Letter size

    # Add header
    page.insert_text(
        (72, 72),
        "Test Document - Unsigned",
        fontsize=16,
        fontname="helv",
    )

    # Add body text
    page.insert_text(
        (72, 120),
        "This is a test PDF document for PDFSigner testing.",
        fontsize=12,
    )

    page.insert_text(
        (72, 150),
        "It should be signed using dry-run mode for E2E tests.",
        fontsize=12,
    )

    # Add footer
    page.insert_text(
        (72, 720),
        "Generated by create_test_pdfs.py",
        fontsize=8,
        color=(0.5, 0.5, 0.5),
    )

    doc.save(str(output_path))
    doc.close()
    print(f"✓ Created: {output_path}")


def create_multipage_pdf(output_path: Path) -> None:
    """Create a multi-page PDF for testing batch operations."""
    print(f"Creating multi-page PDF: {output_path}")

    doc = fitz.open()

    for i in range(3):
        page = doc.new_page(width=612, height=792)  # Letter size

        # Add page number and content
        page.insert_text(
            (72, 72),
            f"Test Document - Page {i + 1}",
            fontsize=16,
            fontname="helv",
        )

        page.insert_text(
            (72, 120),
            f"This is page {i + 1} of a multi-page test document.",
            fontsize=12,
        )

        # Add footer with page number
        page.insert_text(
            (72, 720),
            f"Page {i + 1}/3",
            fontsize=8,
            color=(0.5, 0.5, 0.5),
        )

    doc.save(str(output_path))
    doc.close()
    print(f"✓ Created: {output_path}")


def create_signed_pdf_dry_run(output_path: Path) -> None:
    """Create a signed PDF using dry-run mode (with visual stamp)."""
    print(f"Creating signed PDF (dry-run): {output_path}")

    # Import here to avoid circular imports
    from pdfsigner.core.mock.mock_batch import MockBatchManager

    # Create temporary unsigned PDF
    temp_pdf = output_path.parent / "temp_unsigned.pdf"
    create_unsigned_pdf(temp_pdf)

    try:
        # Sign using dry-run mode
        manager = MockBatchManager()
        result = manager.sign_batch(
            files=[temp_pdf],
            pin="1234",
            visible=True,
            qr_enabled=True,
        )

        if result.all_successful:
            # Move signed PDF to final location
            signed_path = temp_pdf.parent / f"{temp_pdf.stem}_signed{temp_pdf.suffix}"
            signed_path.rename(output_path)
            print(f"✓ Created: {output_path}")
        else:
            print(f"✗ Failed to create signed PDF: {result.error_messages}")

    finally:
        # Clean up temp file
        if temp_pdf.exists():
            temp_pdf.unlink()


def create_signed_pdf_no_qr(output_path: Path) -> None:
    """Create a signed PDF without QR code using dry-run mode."""
    print(f"Creating signed PDF (no QR): {output_path}")

    # Import here to avoid circular imports
    from pdfsigner.core.mock.mock_batch import MockBatchManager

    # Create temporary unsigned PDF
    temp_pdf = output_path.parent / "temp_unsigned_no_qr.pdf"
    create_unsigned_pdf(temp_pdf)

    try:
        # Sign using dry-run mode without QR
        manager = MockBatchManager()
        result = manager.sign_batch(
            files=[temp_pdf],
            pin="1234",
            visible=True,
            qr_enabled=False,
        )

        if result.all_successful:
            # Move signed PDF to final location
            signed_path = temp_pdf.parent / f"{temp_pdf.stem}_signed{temp_pdf.suffix}"
            signed_path.rename(output_path)
            print(f"✓ Created: {output_path}")
        else:
            print(f"✗ Failed to create signed PDF: {result.error_messages}")

    finally:
        # Clean up temp file
        if temp_pdf.exists():
            temp_pdf.unlink()


def create_all_fixtures() -> None:
    """Create all test fixtures."""
    fixtures_dir = Path(__file__).parent

    print("Creating all test fixtures...")
    print("=" * 60)

    # Create unsigned PDFs
    create_unsigned_pdf(fixtures_dir / "sample.pdf")
    create_multipage_pdf(fixtures_dir / "multipage.pdf")

    # Create signed PDFs (dry-run mode)
    create_signed_pdf_dry_run(fixtures_dir / "sample_signed.pdf")
    create_signed_pdf_no_qr(fixtures_dir / "sample_signed_no_qr.pdf")

    print("=" * 60)
    print("✓ All fixtures created successfully!")


def main() -> None:
    """Main entry point."""
    parser = argparse.ArgumentParser(description="Create test PDF fixtures for PDFSigner")
    parser.add_argument(
        "--all",
        action="store_true",
        help="Create all fixtures (default)",
    )
    parser.add_argument(
        "--unsigned",
        action="store_true",
        help="Create only unsigned PDFs",
    )
    parser.add_argument(
        "--signed",
        action="store_true",
        help="Create only signed PDFs",
    )
    parser.add_argument(
        "--multipage",
        action="store_true",
        help="Create only multi-page PDF",
    )

    args = parser.parse_args()
    fixtures_dir = Path(__file__).parent

    # Default to --all if no specific option
    if not (args.unsigned or args.signed or args.multipage):
        args.all = True

    if args.all:
        create_all_fixtures()
    else:
        if args.unsigned:
            create_unsigned_pdf(fixtures_dir / "sample.pdf")

        if args.multipage:
            create_multipage_pdf(fixtures_dir / "multipage.pdf")

        if args.signed:
            create_signed_pdf_dry_run(fixtures_dir / "sample_signed.pdf")
            create_signed_pdf_no_qr(fixtures_dir / "sample_signed_no_qr.pdf")

        print("✓ Done!")


if __name__ == "__main__":
    main()
